---
title: "Module 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Compute Recency, Frequency and Monetary value

```{r}
data <- read.delim(file='purchases.txt', header = F, sep = '\t', dec = '.')
```

```{r}
# Add headers and interpret the last column as a date, extract year of purchase
colnames(data) <- c('customer_id', 'purchase_amount', 'date_of_purchase')
data$date_of_purchase <- as.Date(data$date_of_purchase, '%Y-%m-%d')
data$year_of_purchase <- as.numeric(format(data$date_of_purchase, '%Y'))
data$days_since <- as.numeric(difftime(time1 = '2016-01-01',
                                       time2 = data$date_of_purchase, 
                                       units = 'days'))
```

```{r}
# Display the data after transformation
head(data)
summary(data)
```

```{r}
# Compute key marketing indicators using SQL language
library(sqldf)

# Compute recency, frequency, and average purchase amount
customers_2015 = sqldf("SELECT customer_id,
                               MIN(days_since) AS 'recency',
                               MAX(days_since) AS 'first_purchase',
                               COUNT(*) AS 'frequency',
                               AVG(purchase_amount) AS 'amount'
                        FROM data GROUP BY 1")
```

```{r}
# Explore the data
head(customers_2015)
summary(customers_2015)
hist(customers_2015$recency)
hist(customers_2015$frequency)
hist(customers_2015$amount)
hist(customers_2015$amount, breaks = 100)
```

## Coding a Managerial Segmentation

```{r}
# Simple 2-segment solution using the which statement
customers_2015$segment <- 'NA'
customers_2015$segment[which(customers_2015$recency > 365*3)] = 'inactive'
table(customers_2015$segment)
aggregate(x=customers_2015[, 2:5], by=list(customers_2015$segment), mean)
```

```{r}
# More complex 4-segment solution using which
customers_2015$segment <- 'NA'
customers_2015$segment[which(customers_2015$recency > 365*3)] <- 'inactive'
customers_2015$segment[which(customers_2015$recency <= 365*3 & customers_2015$recency > 365*2)] <- 'cold'
customers_2015$segment[which(customers_2015$recency <= 365*2 & customers_2015$recency > 365*1)] <- 'warm'
customers_2015$segment[which(customers_2015$recency <= 365)] <- 'active'
table(customers_2015$segment)
aggregate(x=customers_2015[, 2:5], by=list(customers_2015$segment), mean)
```

```{r}
# Complete segment solution using which, and exploiting previous test as input
customers_2015$segment <- 'NA'
customers_2015$segment[which(customers_2015$recency > 365*3)] <- 'inactive'
customers_2015$segment[which(customers_2015$recency <= 365*3 & customers_2015$recency > 365*2)] <- 'cold'
customers_2015$segment[which(customers_2015$recency <= 365*2 & customers_2015$recency > 365*1)] <- 'warm'
customers_2015$segment[which(customers_2015$recency <= 365)] <- 'active'
customers_2015$segment[which(customers_2015$segment == "warm" & customers_2015$first_purchase <= 365*2)] <- "new warm"
customers_2015$segment[which(customers_2015$segment == "warm" & customers_2015$amount < 100)] <- "warm low value"
customers_2015$segment[which(customers_2015$segment == "warm" & customers_2015$amount >= 100)] <- "warm high value"
customers_2015$segment[which(customers_2015$segment == "active" & customers_2015$first_purchase <= 365)] <- "new active"
customers_2015$segment[which(customers_2015$segment == "active" & customers_2015$amount < 100)] <- "active low value"
customers_2015$segment[which(customers_2015$segment == "active" & customers_2015$amount >= 100)] <- "active high value"
table(customers_2015$segment)
aggregate(x=customers_2015[, 2:5], by=list(customers_2015$segment), mean)
```

```{r}
# Re-order factor in a way that makes sense
customers_2015$segment <- factor(x=customers_2015$segment, levels = c('inactive', 'cold', 'warm high value', 'warm low value', 'new warm', 'active high value', 'active low value', 'new active'))
table(customers_2015$segment)
aggregate(x=customers_2015[, 2:5], by=list(customers_2015$segment), mean)
```

## Segmenting a database retrospectively

```{r}
# Compute recency, frequency, and average purchase amount
customers_2014 = sqldf("SELECT customer_id,
                               MIN(days_since) - 365 AS 'recency',
                               MAX(days_since) - 365 AS 'first_purchase',
                               COUNT(*) AS 'frequency',
                               AVG(purchase_amount) AS 'amount'
                        FROM data
                        WHERE days_since > 365
                        GROUP BY 1")
```

```{r}
# Complete segment solution using which, and exploiting previous test as input
customers_2014$segment <- 'NA'
customers_2014$segment[which(customers_2014$recency > 365*3)] <- 'inactive'
customers_2014$segment[which(customers_2014$recency <= 365*3 & customers_2014$recency > 365*2)] <- 'cold'
customers_2014$segment[which(customers_2014$recency <= 365*2 & customers_2014$recency > 365*1)] <- 'warm'
customers_2014$segment[which(customers_2014$recency <= 365)] <- 'active'
customers_2014$segment[which(customers_2014$segment == "warm" & customers_2014$first_purchase <= 365*2)] <- "new warm"
customers_2014$segment[which(customers_2014$segment == "warm" & customers_2014$amount < 100)] <- "warm low value"
customers_2014$segment[which(customers_2014$segment == "warm" & customers_2014$amount >= 100)] <- "warm high value"
customers_2014$segment[which(customers_2014$segment == "active" & customers_2014$first_purchase <= 365)] <- "new active"
customers_2014$segment[which(customers_2014$segment == "active" & customers_2014$amount < 100)] <- "active low value"
customers_2014$segment[which(customers_2014$segment == "active" & customers_2014$amount >= 100)] <- "active high value"
```

```{r}
# Re-order factor in a way that makes sense
customers_2014$segment <- factor(x=customers_2014$segment, levels = c('inactive', 'cold', 'warm high value', 'warm low value', 'new warm', 'active high value', 'active low value', 'new active'))
```

```{r}
# Show segmentation results
table(customers_2014$segment)
pie(table(customers_2014$segment), col=rainbow(24))
aggregate(x=customers_2014[, 2:5], by=list(customers_2014$segment), mean)
```

## Compute revenue generation per segment

```{r}
# Notice that people with no revenue in 2015 do NOT appear
revenue_2015 = sqldf("SELECT customer_id, SUM(purchase_amount) AS 'revenue_2015' FROM data WHERE year_of_purchase = 2015 GROUP BY 1")
summary(revenue_2015)
```

```{r}
# Merge 2015 customers and 2015 revenue
actual <- merge(customers_2015, revenue_2015, all.x = TRUE)
```

```{r}
# Replace "NA" with 0
actual$revenue_2015[is.na(actual$revenue_2015)] = 0
```

```{r}
# Show average revenue per customer and per segment
aggregate(x=actual$revenue_2015, by=list(customers_2015$segment), mean)
```

```{r}
# Merge 2014 customers and 2015 revenue
forward <- merge(customers_2014, revenue_2015, all.x = TRUE)
# Replace "NA" with 0
forward$revenue_2015[is.na(forward$revenue_2015)] = 0
```

```{r}
# Show average revenue per customer and per segment
r <- aggregate(x=forward$revenue_2015, by=list(customers_2014$segment), mean)
print(r)
```

```{r}
# Re-order and display results
r <- r[order(r$x, decreasing = TRUE), ]
print(r)
barplot(r$x, names.arg = r$Group.1)
```
