---
title: "Model 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data <- read.delim(file='purchases.txt', header = FALSE, sep = '\t', dec = '.')
```

```{r}
# Add headers and interpret the last column as a date, extract year of purchase
colnames(data) <- c('customer_id', 'purchase_amount', 'date_of_purchase')
data$date_of_purchase <- as.Date(data$date_of_purchase, '%Y-%m-%d')
data$days_since <- as.numeric(difftime(time1 = '2016-01-01',
                                       time2 = data$date_of_purchase, 
                                       units = 'days'))
```

```{r}
# Display the data after transformation
head(data)
summary(data)
```

```{r}
# Compute key marketing indicators using SQL language
library(sqldf)
```

```{r}
# Compute recency, frequency, and average purchase amount
customers = sqldf("SELECT customer_id,
                          MIN(days_since) AS 'recency',
                          COUNT(*) AS 'frequency',
                          AVG(purchase_amount) AS 'amount'
                   FROM data GROUP BY 1")
```

```{r}
# Explore the data
head(customers)
summary(customers)
hist(customers$recency)
hist(customers$frequency)
hist(customers$amount)
hist(customers$amount, breaks = 100)
```

## Prepare and transform the data

```{r}
# Copy customer data into new data frame
new_data <- customers
# Remove customer id as a variable, store it as row names
head(new_data)
row.names(new_data) <- new_data$customer_id
new_data$customer_id <- NULL
head(new_data)
```

```{r}
# Take the log-transform of the amount, and plot
new_data$amount <- log(new_data$amount)
hist(new_data$amount)
```

```{r}
# Standardize variables
new_data <- scale(new_data)
head(new_data)
```

## Running a hierarchical Segmentation

```{r}
# Compute distance metrics on standardized data
# This will likely generate an error on most machines
# d = dist(new_data)
```

```{r}
# Take a 10% sample
sample <- seq(1, 18417, by=10)
head(sample)
customers_sample <- customers[sample, ]
new_data_sample <- new_data[sample, ]
```

```{r}
# Compute distance metrics on standardized data
d = dist(new_data_sample)
```

```{r}
# Perform hierarchical clustering on distance metrics
c <- hclust(d, method = 'ward.D2')
```

```{r}
# Plot the dendogram
plot(c)
```

```{r}
# Cut at 9 segments
members <- cutree(c, k=9)
```

```{r}
# Show first 30 customers, frequency table
members[1:30]
table(members)
```

```{r}
# Show profile of each segment
aggregate(customers_sample[, 2:4], by = list(members), mean)
```
